import type { NextPage,GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
interface Posts {
   posts: {
    body: string;
    comments?: [],
    createdAt: string;
    _id: string;
    title: string;
    indentifier: string;
    slug: string;
    subName?: string;
    updatedAt?: string;
    user?: string;
    userDetails?: {}
   }[]
}

const Home: NextPage<Posts> = ({posts}) => {
  // const {posts} = props;
  console.log(posts)
  console.log(process.env.NEXT_PUBLIC_BASE_URL)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div>
      <h1 className='text-2xl text-rose-500'>Hello nextjs with typescript</h1>
    </div>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch('https://node-api-for-next.herokuapp.com/api/posts')
  const posts: Posts[] = await response.json();
  return {
    props: {
      posts
    }
  }
}

export default Home
// https://youtu.be/wc-5_h6iMn8?list=PLMhAeHCz8S38HfrRtzfzFD5NTbjgQxcpD&t=2122
